# Site settings
title: ButterSus
author: ButterSus
description: >
  A blog about compilers, FPGA, and other things.
  And also burgers
show_excerpts: false

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

# Tags
tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

dash:
  # My cheap VPS running backend for isso comments
  isso:
    url: https://buttersus.duckdns.org

  # Other settings
  date_format: "%b %-d, %Y"
  social_links:
    - url: https://github.com/ButterSus
      icon: github-square
      color: blue
  show_author: true
  animation_speed: 50
  rtl: false
  avatar_source: github
  github_username: ButterSus

# Build settings
remote-theme: jekyll-dash
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - liquid-md5
 - jekyll/tagging
