name: Release Gem
description: Releases a gem to rubygems.

on:
  push:tags
    branches:
      - v1.*
      - v2.*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 🚀 Release gem
        uses: dawidd6/action-publish-gem@v1
        with:
          github_token: ${{secrets.GH_CREDENTIALS}}
          api_key: ${{secrets.RUBYGEMS_API_KEY}}
