name: Build Branch

on: [push]

jobs:
  release:
    if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/2.x' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Release gem
        uses: dawidd6/action-publish-gem@v1
        with:
          github_token: ${{secrets.GH_CREDENTIALS}}
          api_key: ${{secrets.RUBYGEMS_API_KEY}}
